### ISSUE TITLE
2 questions: (1) is there a way to get a trace of results for each iteration, (2) jfnk on my problem gives "ERROR: MethodError: no method matching isless(::ComplexF64, ::ComplexF64)"

### ISSUE THREAD

**Issue by donboyd5** [RJDennis/NLboxsolve.jl#18]
Hi. Thank you for this package.

I am looking to solve a large highly nonlinear unconstrained least squares problem (no box constraints, either):

- 1,000 parameters
- function to calculate residuals involves operations with a data matrix of 40,000 x 20
- it is impractical to calculate analytic gradient and jacobian; I have been using autodiff in other Julia packages

My best approach so far has been to use `LsqFit.lmfit`, which uses Levenberg-Marquardt and is robust but not as fast as I would like.

I have two questions:

1. I have been testing out `nlboxsolve` implementations. (`lm_ar` seems faster than `lm`) However, it would be really helpful to have a way to track a solver's progress - something like `show_trace` in several other packages, with the iteration number and some measure of solution status such as sum of squared residuals, or else the ability to pass a user-defined callback function. I looked through the code but didn't see a parameter that would allow either, but maybe I missed it. Would you mind telling me if there is a way to do this in the `nlboxsolve` function?
2. I am thinking for my problem it would be good to avoid computing the full jacobian, because it seems very time consuming. Thus, I am interested in your `jfnk` method. However, although it works fine on the example problem, on my problem it gives the error message "ERROR: MethodError: no method matching isless(::ComplexF64, ::ComplexF64)". The same problem works with all of the other methods. Would you have advice on what might be causing this problem, and whether you know of a way to fix it?

Many thanks.

**Comment by RJDennis** [comment]
Hi,

1. you are the second person to request show_trace() and/or store_trace() functionality.  Currently I don't have such functionality in the package, but I'll add it since it is a feature people want to have.

2. I think that the problem might be that the function you are trying to find the fix-point of has been typed in a way that preculdes taking complex numbers as an input.  Try setting up your f(x) function so that x can be a vector of Numbers. (EDIT: actually, not sure about this.  Are you able to provide a minimum working example and/or post the error message you got?).

**Comment by RJDennis** [comment]
I've added a solver trace to the solution results in version 0.3.4.

**Comment by donboyd5** [comment]
Thank you! I'll report back on the jfnk issue after I try what you
suggested. I'm away tomorrow but will try the day after.

Don
